//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.28307.137
// 
namespace NetworkVideoPlayerFrontend.VideoServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValueTupleOfstringstringint", Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial struct ValueTupleOfstringstringint : System.ComponentModel.INotifyPropertyChanged {
        
        private string Item1Field;
        
        private string Item2Field;
        
        private int Item3Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Item1 {
            get {
                return this.Item1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Item1Field, value) != true)) {
                    this.Item1Field = value;
                    this.RaisePropertyChanged("Item1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Item2 {
            get {
                return this.Item2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Item2Field, value) != true)) {
                    this.Item2Field = value;
                    this.RaisePropertyChanged("Item2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Item3 {
            get {
                return this.Item3Field;
            }
            set {
                if ((this.Item3Field.Equals(value) != true)) {
                    this.Item3Field = value;
                    this.RaisePropertyChanged("Item3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VideoServiceReference.IFileService")]
    public interface IFileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetFiles", ReplyAction="http://tempuri.org/IFileService/GetFilesResponse")]
        System.Threading.Tasks.Task<string[]> GetFilesAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetFilesPage", ReplyAction="http://tempuri.org/IFileService/GetFilesPageResponse")]
        System.Threading.Tasks.Task<string[]> GetFilesPageAsync(string path, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetDirectories", ReplyAction="http://tempuri.org/IFileService/GetDirectoriesResponse")]
        System.Threading.Tasks.Task<string[]> GetDirectoriesAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetDirectoriesPage", ReplyAction="http://tempuri.org/IFileService/GetDirectoriesPageResponse")]
        System.Threading.Tasks.Task<string[]> GetDirectoriesPageAsync(string path, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/IsFileProvided", ReplyAction="http://tempuri.org/IFileService/IsFileProvidedResponse")]
        System.Threading.Tasks.Task<bool> IsFileProvidedAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/IsProvidingFile", ReplyAction="http://tempuri.org/IFileService/IsProvidingFileResponse")]
        System.Threading.Tasks.Task<bool> IsProvidingFileAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/StartProvideFile", ReplyAction="http://tempuri.org/IFileService/StartProvideFileResponse")]
        System.Threading.Tasks.Task<string> StartProvideFileAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/ProvideFile", ReplyAction="http://tempuri.org/IFileService/ProvideFileResponse")]
        System.Threading.Tasks.Task<string> ProvideFileAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetFileId", ReplyAction="http://tempuri.org/IFileService/GetFileIdResponse")]
        System.Threading.Tasks.Task<string> GetFileIdAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/UnprovideFile", ReplyAction="http://tempuri.org/IFileService/UnprovideFileResponse")]
        System.Threading.Tasks.Task UnprovideFileAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/UnprovideFileForAll", ReplyAction="http://tempuri.org/IFileService/UnprovideFileForAllResponse")]
        System.Threading.Tasks.Task UnprovideFileForAllAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetProvidedFiles", ReplyAction="http://tempuri.org/IFileService/GetProvidedFilesResponse")]
        System.Threading.Tasks.Task<NetworkVideoPlayerFrontend.VideoServiceReference.ValueTupleOfstringstringint[]> GetProvidedFilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetProvidedFilesPage", ReplyAction="http://tempuri.org/IFileService/GetProvidedFilesPageResponse")]
        System.Threading.Tasks.Task<NetworkVideoPlayerFrontend.VideoServiceReference.ValueTupleOfstringstringint[]> GetProvidedFilesPageAsync(int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetBasePath", ReplyAction="http://tempuri.org/IFileService/GetBasePathResponse")]
        System.Threading.Tasks.Task<string> GetBasePathAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetTime", ReplyAction="http://tempuri.org/IFileService/GetTimeResponse")]
        System.Threading.Tasks.Task<string> GetTimeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileServiceChannel : NetworkVideoPlayerFrontend.VideoServiceReference.IFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileServiceClient : System.ServiceModel.ClientBase<NetworkVideoPlayerFrontend.VideoServiceReference.IFileService>, NetworkVideoPlayerFrontend.VideoServiceReference.IFileService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FileServiceClient() : 
                base(FileServiceClient.GetDefaultBinding(), FileServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IFileService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(FileServiceClient.GetBindingForEndpoint(endpointConfiguration), FileServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FileServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FileServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<string[]> GetFilesAsync(string path) {
            return base.Channel.GetFilesAsync(path);
        }
        
        public System.Threading.Tasks.Task<string[]> GetFilesPageAsync(string path, int pageSize, int pageIndex) {
            return base.Channel.GetFilesPageAsync(path, pageSize, pageIndex);
        }
        
        public System.Threading.Tasks.Task<string[]> GetDirectoriesAsync(string path) {
            return base.Channel.GetDirectoriesAsync(path);
        }
        
        public System.Threading.Tasks.Task<string[]> GetDirectoriesPageAsync(string path, int pageSize, int pageIndex) {
            return base.Channel.GetDirectoriesPageAsync(path, pageSize, pageIndex);
        }
        
        public System.Threading.Tasks.Task<bool> IsFileProvidedAsync(string path) {
            return base.Channel.IsFileProvidedAsync(path);
        }
        
        public System.Threading.Tasks.Task<bool> IsProvidingFileAsync(string path) {
            return base.Channel.IsProvidingFileAsync(path);
        }
        
        public System.Threading.Tasks.Task<string> StartProvideFileAsync(string path) {
            return base.Channel.StartProvideFileAsync(path);
        }
        
        public System.Threading.Tasks.Task<string> ProvideFileAsync(string path) {
            return base.Channel.ProvideFileAsync(path);
        }
        
        public System.Threading.Tasks.Task<string> GetFileIdAsync(string path) {
            return base.Channel.GetFileIdAsync(path);
        }
        
        public System.Threading.Tasks.Task UnprovideFileAsync(string path) {
            return base.Channel.UnprovideFileAsync(path);
        }
        
        public System.Threading.Tasks.Task UnprovideFileForAllAsync(string path) {
            return base.Channel.UnprovideFileForAllAsync(path);
        }
        
        public System.Threading.Tasks.Task<NetworkVideoPlayerFrontend.VideoServiceReference.ValueTupleOfstringstringint[]> GetProvidedFilesAsync() {
            return base.Channel.GetProvidedFilesAsync();
        }
        
        public System.Threading.Tasks.Task<NetworkVideoPlayerFrontend.VideoServiceReference.ValueTupleOfstringstringint[]> GetProvidedFilesPageAsync(int pageSize, int pageIndex) {
            return base.Channel.GetProvidedFilesPageAsync(pageSize, pageIndex);
        }
        
        public System.Threading.Tasks.Task<string> GetBasePathAsync() {
            return base.Channel.GetBasePathAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetTimeAsync() {
            return base.Channel.GetTimeAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFileService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFileService)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:6428/FileService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return FileServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IFileService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return FileServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IFileService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IFileService,
        }
    }
}
